* STATA command file generated by EUGene  3.10 to read data file
* 
* To execute this command file: 
*    1) Run STATA,
*    2) "cd" to directory "C:\bls\empirical\",
*    3) enter command "do bls.data.raw.do".

* Number of observations in this data set: 693351

* Data set specifications:
*   Base Format: Non-directed Dyad
*   Time Span: 1816 to 2002
*   Selected Subset: All dyads included)
*   Sampling: None (100% of available data written to file)
*   Variables included:
*        ccode1	ccode2	year	cap_1	cap_2	majpow1	majpow2	alliance	dem1	dem2	contig	distance	numstate	numGPs	syscon	mzongo	mzongonm	mzmid	mzmidnm	mzhost1	mzhost2	mzhostd	mzkeynum	mzjoany	mzjomid	mzhiactd	mzfatald	mzcowwar	dtrade	ttrade1	ttrade2	dependa	dependb	democ1	democ2	autoc1	autoc2	polity1	polity2	xrreg1	xrreg2	xrcomp1	xrcomp2	xropen1	xropen2	xconst1	xconst2	parreg1	parreg2	parcomp1	parcomp2	exrec1	exrec2	exconst1	exconst2	polcomp1	polcomp2
*   Selected settings for variables with multiple output options:
*        Alliances taken from COW dyadic alliance file
*        Distance variable measured using capitol coordinates only (no contiguity)
*        Peace years calculated without Werner peace year adjustment
*       Dispute characteristics:
*        When two or more disputes occur in a year, data is from the highest intensity dispute
*        Disputes marked for originators only
*        All dyad-years with an ongoing MID included
*        Ongoing dispute years not considered new initiations
*        Joiner Dyads dropped

* Note:  EUGene draws on datasets originally published elsewhere by other scholars.  When 
* presenting analysis using data generated by EUGene, please cite the original data sources 
* as well as EUGene (see EUGene documentation, Appendix D) 
*
* Bibliography for this data set:
* Gibler, Douglas M., and Meredith Sarkees. 2002. "Coding Manual for v3.0 of the Correlates of War Formal Interstate Alliance Data set, 1816-2000." Typescript. 
* Jaggers, Keith, and Ted Robert Gurr.  1995.  "Tracking Democracy's Third Wave with the Polity III Data."  Journal of Peace Research 32:469-482.
* Maoz, Zeev.  1999.  "Dyadic Militarized Interstate Disputes, version 1.1."  Available at ftp://spirit.tau.ac.il/zeevmaoz/dyadmid.doc
* Reiter, Dan.  2000.  "Interstate Alliances, 1985-1992: version 2."  Unpublished memorandum.
* Singer, J. David, Stuart Bremer, and John Stuckey.  1972.  "Capability Distribution, Uncertainty, and Major Power War, 1820-1965."  in Bruce Russett, ed.  	Peace, War and Numbers.  Beverly Hills:  Sage.
* Small, Melvin, and J. David Singer.  1969.  "Formal Alliances, 1815-1965:  An Extension of the Basic Data."  Journal of Peace Research 6: 257-282.  
* Small, Melvin, and J. David Singer.  1982.  Resort to Arms:  International and Civil Wars, 1816-1980.  Beverly Hills:  Sage Publications.
* Werner, Suzanne.  2000.  "The Effects of Political Similarity on the Onset of Militarized Disputes, 1816-1985."  Political Research Quarterly 53(2): 343-374.
* Barbieri, Katherine. 1996. Economic Interdependence and Militarized Interstate Conflict, 1870-1985, Ph.D. Dissertation. Binghamton University, Binghamton, NY.
* Barbieri, Katherine. 1996. Economic Interdependence and Militarized Interstate Conflict, 1870-1985, Ph.D. Dissertation. Binghamton University, Binghamton, NY.
* Oneal, John R., and Bruce Russett.  1999.  Assessing the Liberal Peace with Alternative Specifications: Trade Still Reduces Conflict.  Journal of Peace Research 36: 423-32.
* Marshall, Monty G. and Keith Jaggers. 2002. Polity IV Project: Political Regime Characteristics and Transitions, 1800-2002. http://www.cidcm.umd.edu/inscr/polity/index.htm.

#delimit ;
cd "~/bls/empirical/";
set more off;
clear all;
set memory 171817k;

infile int ccode1 int ccode2 int year float cap_1 float cap_2 byte majpow1 byte majpow2 byte alliance byte dem1 byte dem2 byte contig float distance int numstate int numGPs float syscon int mzongo int mzongonm int mzmid int mzmidnm int mzhost1 int mzhost2 byte mzhostd int mzkeynum byte mzjoany byte mzjomid byte mzhiactd int mzfatald byte mzcowwar float dtrade float ttrade1 float ttrade2 float dependa float dependb long democ1 long democ2 long autoc1 long autoc2 long polity1 long polity2 long xrreg1 long xrreg2 long xrcomp1 long xrcomp2 long xropen1 long xropen2 long xconst1 long xconst2 long parreg1 long parreg2 long parcomp1 long parcomp2 long exrec1 long exrec2 long exconst1 long exconst2 long polcomp1 long polcomp2  using bls.data.raw;

* The next command drops the case that was read 
*  if the user included a line of variable names;

drop if missing(ccode1) | missing(year);

* Interpret missing values; 
mvdecode ccode1 ccode2 year cap_1 cap_2 majpow1 majpow2 alliance contig distance numstate numGPs syscon mzongo mzongonm mzmid mzmidnm mzhost1 mzhost2 mzhostd mzkeynum mzjoany mzjomid mzhiactd mzfatald mzcowwar syscon ttrade1 ttrade2 dtrade dependa dependb  , mv(-9);

mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  exrec1 exrec2 exconst1 exconst2 polcomp1 polcomp2, mv(-9);
mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  dem1 dem2 polity1 polity2  exrec1 exrec2 exconst1 exconst2, mv(-99);
mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  dem1 dem2 polity1 polity2 exrec1 exrec2 exconst1 exconst2 polcomp1 polcomp2, mv(-88);
mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  dem1 dem2 polity1 polity2  exrec1 exrec2 exconst1 exconst2 polcomp1 polcomp2, mv(-77);
mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  dem1 dem2 polity1 polity2  exrec1 exrec2 exconst1 exconst2 polcomp1 polcomp2, mv(-66);
mvdecode democ1 democ2 autoc1 autoc2 xrreg1 xrreg2 xrcomp1 xrcomp2 xropen1 xropen2 xconst1 xconst2 parreg1 parreg2 parcomp1 parcomp2  dem1 dem2 polity1 polity2  exrec1 exrec2 exconst1 exconst2 polcomp1 polcomp2 dtrade ttrade1 ttrade2, mv(-999);

compress;

save bls.data.raw.dta, replace;



